version: '2'
services:
  wordpress:
    build: ./wordpress
    labels: 
      - "traefik.frontend.rule=Host:www2.chris-kelly.net"
      - "traefik.docker.network=traefik"
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=wordpressuser
      - WORDPRESS_DB_PASSWORD=###change_me###
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - traefik
      - back-end
    links:
      - mysql
  mysql:
    image: mysql:5.7
    labels:
      - "traefik.enable=false"
    environment:
      - MYSQL_ROOT_PASSWORD=###root_change_me###
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpressuser
      - MYSQL_PASSWORD=###change_me###
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - back-end
volumes:
  wordpress-data:
    driver: local
  mysql-data:
    driver: local
networks:
  traefik:
    external:
      name: traefik
  back-end:
    driver: bridge
